// <auto-generated />
namespace MyRoommate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_messages));
        
        string IMigrationMetadata.Id
        {
            get { return "202003230210500_added_messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
